### Creates new entity
POST http://localhost:4000/patients/createPatient
Content-Type: application/json

{
  "name": "omkar",
  "email": "omkar121@gmail.com",
  "address": "Thane",
  "dateOfBirth": "2001-11-19",
  "registerDate": "2025-05-24"
}

###