### Creates new entity
#POST http://localhost:4000/patients/createPatient
#POST http://localhost:4004/api/patients/createPatient
POST http://lb-360c51a7.elb.localhost.localstack.cloud:4000/patients/createPatient
Content-Type: application/json

{
  "name": "omkar api gateway test",
  "email": "localstack_test@gmail.com",
  "address": "Thane",
  "dateOfBirth": "2001-11-19",
  "registerDate": "2025-05-24"
}

###