### GET request to get all patients
#GET http://localhost:4000/patients/getPatients
#GET  http://localhost:4004/api/patients/getPatients
GET http://lb-360c51a7.elb.localhost.localstack.cloud:4000/patients/getPatients
Authorization: Bearer {{token}}
###